name = "website-trunghai"
main = ".open-next/worker.js"
account_id = "b7ea767effeb7ee6eaa71e34a83c0a37"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "trunghai-db"
database_id = "80d93ff3-f66a-4eba-a331-6caa6cf72b21"

[vars]
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "syjvx1ly"
NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = "trunghai_uploads"
CLOUDFLARE_ACCOUNT_ID = "b7ea767effeb7ee6eaa71e34a83c0a37"
CLOUDFLARE_D1_DATABASE_ID = "80d93ff3-f66a-4eba-a331-6caa6cf72b21"
