name = "website-trunghai"
pages_build_output_dir = ".open-next"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "website-trunghai"
database_id = "29fc183a-7dbd-4763-acd1-686d01886113"

[vars]
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "syjvx1ly"
NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = "trunghai_uploads"
CLOUDFLARE_ACCOUNT_ID = "52f76df902421a88a4a54e48bcee0321"
CLOUDFLARE_D1_DATABASE_ID = "29fc183a-7dbd-4763-acd1-686d01886113"
