name = "website-trunghai"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "trunghai-db"
database_id = "29fc183a-7dbd-4763-acd1-686d01886113"
